from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class Recommendation:
    """
    A fantasy football recommendation generated by Cortex.
    """

    entity_type: str
    entity_name: str

    action: str

    confidence: float

    score_delta: float

    team: Optional[str] = None

    reasons: List[str] = field(default_factory=list)

    recommendation_type: str = "redraft"

    timeframe: str = "current"
