import streamlit as st


def render_player_snapshot(result):
    """
    Render player scorecards produced by the Cortex engine.
    """
    st.markdown("### Player Scorecard")
    st.caption("Scorecards are generated by the Cortex Score Engine.")

    if not result.player_snapshots:
        st.info("No player scorecard was generated.")
        return

    for snapshot in result.player_snapshots:
        st.write(
            f"**{snapshot.name}** "
            f"({snapshot.team or 'UNK'})"
        )

        prediction = snapshot.prediction

        if prediction is None:
            continue

        st.markdown("#### Forecast")

        col1, col2, col3, col4 = st.columns(4)

        col1.metric(
            "Trend",
            prediction.projected_trend,
        )

        col2.metric(
            "Projected Score",
            f"{prediction.projected_score:.2f}",
            delta=f"{prediction.score_delta:+.2f}",
        )

        col3.metric(
            "Confidence",
            f"{prediction.confidence * 100:.0f}%",
        )

        col4.metric(
            "Horizon",
            f"{prediction.horizon_days} days",
        )

        if prediction.reasons:
            st.markdown("**Forecast reasons**")

            for reason in prediction.reasons:
                st.write(f"- {reason}")
