import streamlit as st


def render_player_scorecard(result):
    """
    Render player scorecards produced by the Cortex engine.
    """
    st.markdown("### Player Scorecard")
    st.caption("Scorecards are generated by the Cortex Score Engine.")

    if not result.player_scorecards:
        st.info("No player scorecard was generated.")
        return

    for scorecard in result.player_scorecards:
        st.write(
            f"**{scorecard.player_name}** "
            f"({scorecard.team or 'UNK'})"
        )

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Overall", f"{scorecard.overall_score:.1f}")
            st.metric(
                "Opportunity",
                f"{scorecard.opportunity_score:.1f}",
            )

        with col2:
            st.metric("Health", f"{scorecard.health_score:.1f}")
            st.metric(
                "Momentum",
                f"{scorecard.momentum_score:.1f}",
            )

        with col3:
            st.metric("Risk", f"{scorecard.risk_score:.1f}")
            st.metric("Hype", f"{scorecard.hype_score:.1f}")
